
title: My Portfolio Website
baseurl: '/'



# Profile information
yourname: Andrei Rusu
title: 'Technology Analyst Intern'
location: London , UK


## Social Profiles
facebook: https://www.facebook.com/rusu.c.andrei  ## your facebook account url
linkedin: https://www.linkedin.com/in/andrei-rusu-5a0a89106/  ## your linkedin account url
github: https://github.com/andrei-rusu



# Update all the sections by editing the files inside _includes folder.
